# -*- coding: utf-8 -*-
"""Python Publish.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pq5ANGnbex5MmTDZOB9CnsCuj689G6HX
"""

#!pip install -q paho-mqtt

import struct
import time
import random
import paho.mqtt.client as mqtt

# ============================================================
# MQTT CONFIGURATION
# ============================================================

BROKER = "test.mosquitto.org"
PORT = 1883
SEND_TOPIC = "transmitcontrolsignals/roboticarm/orange_bird"
SEND_INTERVAL = 1.0

# ============================================================
# VALUE LIMITS (min, max) for each of the 5 values
# ============================================================

LIMITS = [
    (0.0, 1.0),  # Value 1
    (1.0, 2.0),  # Value 2
    (2.0, 3.0),  # Value 3
    (3.0, 4.0),  # Value 4
    (4.0, 5.0),  # Value 5
]


def generate_values():
    """Generate one random value inside each limit."""
    return [random.uniform(lo, hi) for lo, hi in LIMITS]


def enforce_limits(values):
    """Clamp values to their limits (safety net if values come from elsewhere)."""
    return [min(max(v, lo), hi) for v, (lo, hi) in zip(values, LIMITS)]


# ============================================================
# CALLBACKS
# ============================================================

def on_connect(client, userdata, flags, rc):
    if rc == 0:
        print(f"Connected to {BROKER}:{PORT}")
    else:
        print(f"Connection failed. Return code: {rc}")


def on_disconnect(client, userdata, rc):
    print("Disconnected normally." if rc == 0 else f"Disconnected unexpectedly. rc={rc}")


def on_publish(client, userdata, mid):
    print(f"Published. Message ID: {mid}")


# ============================================================
# MAIN
# ============================================================

client = mqtt.Client()
client.on_connect = on_connect
client.on_disconnect = on_disconnect
client.on_publish = on_publish

print("=" * 60)
print("               MQTT FLOAT32 SENDER")
print("=" * 60)
print(f"Send topic : {SEND_TOPIC}")
for i, (lo, hi) in enumerate(LIMITS, 1):
    print(f"Value {i} limit: {lo} to {hi}")
print("=" * 60)

try:
    client.connect(BROKER, PORT, 60)
except Exception as e:
    print(f"ERROR connecting to MQTT: {e}")
    exit(1)

client.loop_start()
time.sleep(2)

try:
    while True:
        values_to_send = enforce_limits(generate_values())

        # 5 little-endian float32 values = 20 bytes (matches JS setFloat32(..., true))
        payload = struct.pack("<5f", *values_to_send)

        print("\n" + "=" * 60)
        print("                  SENDING")
        print("=" * 60)
        for i, value in enumerate(values_to_send, 1):
            print(f"Value {i}: {value:.6f}")
        print(f"Raw bytes: {payload!r}")

        try:
            result = client.publish(SEND_TOPIC, payload, qos=0)
            if result.rc != mqtt.MQTT_ERR_SUCCESS:
                print(f"ERROR publishing. Return code: {result.rc}")
        except Exception as e:
            print(f"ERROR while publishing: {e}")

        time.sleep(SEND_INTERVAL)

except KeyboardInterrupt:
    print("\nStopping...")

finally:
    client.loop_stop()
    client.disconnect()
    print("MQTT connection closed.")