# -*- coding: utf-8 -*-
"""Python Subscribe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T0iw_XkC9eMyS3ONdRxqrexJ2aBgPwfw
"""

#!pip install -q paho-mqtt

import struct
import paho.mqtt.client as mqtt

# ============================================================
# MQTT CONFIGURATION
# ============================================================

BROKER = "test.mosquitto.org"
PORT = 1883
RECEIVE_TOPIC = "transmitcontrolsignals/roboticarm"

EXPECTED_BYTES = 20  # 5 x float32


# ============================================================
# CALLBACKS
# ============================================================

def on_connect(client, userdata, flags, rc):
    if rc == 0:
        print(f"Connected to {BROKER}:{PORT}")
        result, _ = client.subscribe(RECEIVE_TOPIC, qos=0)
        if result == mqtt.MQTT_ERR_SUCCESS:
            print(f"Subscribed to: {RECEIVE_TOPIC}")
        else:
            print(f"ERROR subscribing. Return code: {result}")
    else:
        print(f"Connection failed. Return code: {rc}")


def on_disconnect(client, userdata, rc):
    print("Disconnected normally." if rc == 0 else f"Disconnected unexpectedly. rc={rc}")


def on_message(client, userdata, msg):
    print("\n" + "=" * 60)
    print("              MQTT MESSAGE RECEIVED")
    print("=" * 60)
    print(f"Topic       : {msg.topic}")
    print(f"Byte length : {len(msg.payload)}")
    print(f"Raw bytes   : {msg.payload!r}")

    if len(msg.payload) != EXPECTED_BYTES:
        print(f"\nERROR: expected {EXPECTED_BYTES} bytes (5 x float32), "
              f"got {len(msg.payload)}.")
        return

    try:
        values = struct.unpack("<5f", msg.payload)
    except struct.error as e:
        print(f"\nERROR decoding float32 data: {e}")
        return

    print("\n========== RECEIVED VALUES ==========")
    for i, value in enumerate(values, 1):
        print(f"Value {i}: {value:.3f}")
    print("=" * 60)


# ============================================================
# MAIN
# ============================================================

client = mqtt.Client()
client.on_connect = on_connect
client.on_disconnect = on_disconnect
client.on_message = on_message

print("=" * 60)
print("              MQTT FLOAT32 RECEIVER")
print("=" * 60)
print(f"Receive topic : {RECEIVE_TOPIC}")
print("=" * 60)

try:
    client.connect(BROKER, PORT, 60)
except Exception as e:
    print(f"ERROR connecting to MQTT: {e}")
    exit(1)

try:
    client.loop_forever()
except KeyboardInterrupt:
    print("\nStopping...")
finally:
    client.disconnect()
    print("MQTT connection closed.")